services:
  db:
    image: mysql
    container_name: db
    hostname: kernels_database
    environment:
      MYSQL_DATABASE: kp
      MYSQL_USER: developer
      MYSQL_PASSWORD_FILE: /run/secrets/db_dev_password.txt
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password.txt
    ports:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p", "$$(cat /run/secrets/db_root_password.txt)"]
      start_period: 30s
      interval: 30s
      timeout: 30s
      retries: 5
    secrets:
      - db_dev_password
      - db_root_password


  api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    container_name: api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: kernels_database
      DATABASE_PORT: 3306
      DATABASE_USER: developer
      DATABASE_PASSWORD_FILE: /run/secrets/db_dev_password.txt
    secrets:
      - db_dev_password

secrets:
  db_dev_password:
    file: src/db/dev_password.txt
  db_root_password:
    file: src/db/root_password.txt
